export enum MediaCollectionType {
  USER = 'USER',
  COMPANY = 'COMPANY',
  BRAND = 'BRAND',
  LIFESTYLE = 'LIFESTYLE',
  AMENITY = 'AMENITY',
  RANKING_CATEGORY = 'RANKING_CATEGORY',
  RESIDENCE = 'RESIDENCE',
  RESIDENCE_UNIT = 'RESIDENCE_UNIT',
  CAREER_CONTACT_FORM = 'CAREER_CONTACT_FORM',
  CONTACT_FORM = 'CONTACT_FORM',
  CLAIM_PROFILE_CONTACT_FORM = 'CLAIM_PROFILE_CONTACT_FORM',
}
