export enum EmailTemplatesEnum {
  RESET_PASSWORD = 'reset-password',
  WELCOME = 'welcome',
  VERIFY_EMAIL = 'verify-email',
  INVITE = 'invite',
  FORGOT_PASSWORD = 'forgot-password',
  CLAIM_REQUEST = 'claim-request',
  CLAIM_REQUEST_APPROVED = 'claim-request-approved',
  CUSTOMER_REQUEST_REVIEW = 'customer-request-review',
  CUSTOMER_SUPPORT_ACKNOWLEDGMENT = 'customer-support-acknowledgment',
  INITAL = 'initial',
  JOB_APPLICATION = 'job-application',
  LOW_STAR_REVIEW = 'low-star-review',
  ON_FORM_SUBMIT = 'on-form-submit',
  REJECTED_CLAIM_REQUEST = 'rejected-claim-request',
  REQUEST_REVIEW = 'request-review',
  REVIEW_RESPONSE = 'review-response',
  REVIEW_WEEKLY_SUMMARY = 'review-weekly-summary',
  SPECIFIC_WORDS_REVIEW = 'specific-words-review',

  CONTACT_CONSULTATION = 'contact-consultation',
  REQUEST_INFORMATION = 'request-information',
  CONTACT_US = 'contact-us',
  B2B_FORM = 'b2b-form',
  SUBMIT_REVIEW = 'submit-review',
  REPORT_AN_ERROR = 'report-an-error',
  APPLY_FOR_RANKING = 'apply-for-ranking',
  REQUEST_PREMIUM_PROFILE = 'request-premium-profile',
  PREMIUM_SUBSCRIPTION = 'premium-subscription',
  REGISTER_RESIDENCE = 'register-residence',
  REGISTER_UNIT = 'register-unit',
  SUGGEST_FEATURE = 'suggest-feature',

  ACCEPTED_RESIDENCE = 'accepted-residence',
  REJECTED_RESIDENCE = 'rejected-residence',
  OWNERSHIP_REQUEST = 'ownership-request',
  OWNERSHIP_REQUEST_ACCEPTED = 'ownership-request-accepted',
  OWNERSHIP_REQUEST_DECLINED = 'ownership-request-declined',
}
